project:
  type: website

website:
  favicon: static/favicon.ico
  title: "Quarto Pressmark"
  llms-txt: true
  open-graph:
    site-name: "Quarto Pressmark"
  site-url: https://mdwm.org/quarto-pressmark/
  description: "Pressmark - elegant, typographic, and minimalistic Quarto theme for blogs and personal websites."
  search: true
  navbar:
    title: "Pressmark"
    logo: static/P.png
    logo-alt: "Quarto Pressmark Logo"
    collapse-below: lg
    right: 
      - text: "Features"
        href: features/index.qmd
      - text: "Setup"
        href: setup.qmd
  page-navigation: true
  back-to-top-navigation: false
  page-footer:
    left: |
      © 2026, built with <a href='https://quarto.org' target='_blank'>Quarto</a> and the <a href='https://mdwm.org/quarto-pressmark/' target='_blank'>Pressmark</a> theme
    right:
      - text: GitHub
        href: "https://github.com/skriptum/quarto-pressmark"

# HTML format options
format:
  html:
    theme: pressmark.scss # magic line to use the custom SCSS theme !IMPORTANT!
    toc: true # show the table of contents by default
    toc-location: body # show the TOC in the body of the page, better for mobile devices
    html-math-method: katex # KaTex is faster and smaller than MathJax
    link-external-icon: false # enable if you want to show an icon next to external links
    link-external-newwindow: true # open external links in a new window
